### ISSUE TITLE
LCd error

### ISSUE THREAD

**Issue by dodgey99** [DesignSparkrs/RadioGlobe#3]
Finished the build and nothing happens at all. Blank LCD. I can try to start it via SSH and thsi happens:

pi@radioglobe:~/work/RadioGlobe $ python3 main.py
Rebuilding map
Saving map
Done
Traceback (most recent call last):
File "main.py", line 142, in <module>
display_thread = Display(3, "Display")
File "/home/pi/work/RadioGlobe/display.py", line 16, in __init__
self.lcd = liquidcrystal_i2c.LiquidCrystal_I2C(DISPLAY_I2C_ADDRESS, DISPLAY_ I2C_PORT, numlines=DISPLAY_ROWS)
AttributeError: module 'liquidcrystal_i2c' has no attribute 'LiquidCrystal_I2C'
^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
t.join()
File "/usr/lib/python3.7/threading.py", line 1032, in join
self._wait_for_tstate_lock()
File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
elif lock.acquire(block, timeout):
KeyboardInterrupt

**Comment by dodgey99** [comment]
Reinstalled buster

**Comment by petenwood** [comment]
> Reinstalled buster

Hi @dodgey99 , did re installing Buster solve the problem ok?

**Comment by dodgey99** [comment]
It did thanks. 1st install was a full install. Re install was buster lite. Then when i installed radio globe it downloaded all the dependencies, which I guess it missed some of on the previous install
